#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jan 26 01:37:21 2011

import wx
from MyFrame import MyFrame

class MiApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()
        frame_1 = MyFrame(None, -1, "")
        self.SetTopWindow(frame_1)
        frame_1.Show()
        return 1

# end of class MiApp

if __name__ == "__main__":
    Fiscal3G = MiApp(0)
    Fiscal3G.MainLoop()
