# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jan 26 01:37:21 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from reports_list import Reports_list
from Tabs import Tabs
# end wxGlade

class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FULL_REPAINT_ON_RESIZE|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        
        # Tool Bar
        self.frame_1_toolbar = wx.ToolBar(self, -1, style=wx.TB_HORIZONTAL|wx.TB_TEXT|wx.TB_HORZ_LAYOUT|wx.TB_HORZ_TEXT)
        self.SetToolBar(self.frame_1_toolbar)
        self.frame_1_toolbar.AddLabelTool(1, "SMS", wx.Bitmap("GartoonRedux/32x32/actions/document-send.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddLabelTool(2, "Agregar", wx.Bitmap("GartoonRedux/32x32/actions/contact-new.png", wx.BITMAP_TYPE_ANY), wx.NullBitmap, wx.ITEM_NORMAL, "", "")
        self.frame_1_toolbar.AddSeparator()
        # Tool Bar end
        self.label_report = wx.StaticText(self, -1, "Reportes", style=wx.ALIGN_CENTRE)
        self.label_log = wx.StaticText(self, -1, "LOG", style=wx.ALIGN_CENTRE)
        #Tab
        self.tab_report = Tabs(self, -1, "Reportes", style=wx.EXPAND)
        #Tabs end
        self.__set_properties()
        self.__do_layout()
        
        self.Bind(wx.EVT_TOOL, self.OnAgregar, id = 2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle("Fiscal3G")
        self.frame_1_toolbar.Realize()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_main = wx.BoxSizer(wx.VERTICAL)
        sizer_main.Add(self.label_report, 0, wx.ALL|wx.EXPAND, 0)
        sizer_main.Add(self.tab_report, 0, wx.ALL|wx.EXPAND, 0)
        sizer_main.Add(self.label_log, 0, wx.ALL|wx.EXPAND, 0)
        self.SetSizer(sizer_main)
        sizer_main.Fit(self)
        sizer_main.SetSizeHints(self)
        self.Layout()
        self.Centre()
        # end wxGlade
    
    def add_tab_to_frame(self):
        tab = Tabs(MyFrame)
        
    
    def OnAgregar(self, event):
        #print "apretando agregar"
        self.add_tab_to_frame()
        event.Skip()
    
# end of class MyFrame


