# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Jan 26 13:20:35 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class Tabs(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Tabs.__init__
        kwds["style"] = wx.SIMPLE_BORDER|wx.FULL_REPAINT_ON_RESIZE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Tabs.__set_properties
        self.SetTitle("Reportes")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Tabs.__do_layout
        sizer_tab = wx.BoxSizer(wx.VERTICAL)
        sizer_tab_list = wx.BoxSizer(wx.HORIZONTAL)
        self.notebook_1_pane_1.SetSizer(sizer_tab_list)
        self.notebook.AddPage(self.notebook_1_pane_1, "")
        sizer_tab.Add(self.notebook, 1, wx.ALL|wx.EXPAND, 0)
        self.SetSizer(sizer_tab)
        sizer_tab.Fit(self)
        self.Layout()
        # end wxGlade

# end of class Tabs


